name: Metrics
on:
  schedule:
    - cron: "30 3 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}   # fine-grained token: read public repos
          user: Larusdi
          filename: metrics.svg                 # disimpan di root repo
          output_action: commit                 # PENTING: commit ke repo
          committer_branch: main                # ganti jika default branch bukan main
          config_timezone: Asia/Jakarta
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_ignored: html
          plugin_isocalendar: yes
