name: Metrics

on:
  schedule:
    - cron: "30 3 * * *"      # tiap hari 03:30 UTC
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Larusdi
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Jakarta
          filename: metrics.svg
          config_display: large
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_indepth: yes
          plugin_languages_ignored: html
          plugin_languages_limit: 8
          plugin_achievements: yes
          plugin_achievements_threshold: X
          plugin_habits: yes
          plugin_habits_from: 200       # depth commit history
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_lines: yes
