name: metrics
on:
  schedule: [ { cron: "30 3 * * *" } ]   # jalan tiap hari 03:30 UTC
  workflow_dispatch:                      # bisa run manual

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write                     # agar bisa commit metrics.svg
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}   # sudah kamu buat sebagai secret
          user: Larusdi
          filename: metrics.svg                 # disimpan di root repo
          output_action: commit                 # wajib: commit file
          committer_branch: main                # ganti jika default branch bukan 'main'
          config_timezone: Asia/Jakarta
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_ignored: html
          plugin_isocalendar: yes
