name: Generate Snake

on:
  schedule:
    - cron: "0 3 * * *"   # tiap hari 03:00 UTC
  workflow_dispatch:

concurrency:
  group: snake-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate Snake (Light + Dark)
        uses: Platane/snk@v3
        with:
          github_user_name: Larusdi
          outputs: |
            dist/snake.svg?palette=github-light&color_snake=%2300C853&color_dots=%23000000,%23333333,%23999999,%23FFFFFF
            dist/snake-dark.svg?palette=github-dark&color_snake=%23FF2FB9&color_dots=%23FFFFFF,%23B0B7C3,%23374759,%230B0F19

      - name: Upload preview artifact
        uses: actions/upload-artifact@v4
        with:
          name: snake-preview
          path: dist

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
